version: '3'
services:
  proxy:
    image: nginx:alpine
    container_name: proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./web/php:/var/www/html
      - ./etc/nginx/default.conf:/etc/nginx/conf.d/default.conf

  php:
    build: ./web/php
    container_name: php
    volumes:
      - ./web/php:/var/www/html
  
  react:
    build: ./web/react
    container_name: react
    ports:
      - "3000:3000"
  